### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by cfriedt**
6 commits - please see each commit message for details.

With this we are able to reproduce all test results internally.

### CODE REVIEW

**Comment by cfriedt** [comment]
I should note that `checkpatch.pl` is pretty horrible with C++ syntax.

E.g. - this makes no sense fwict.
```shell
ERROR: need consistent spacing around '*' (ctx:WxV)
#86: FILE: ./src/server.c:86:
+			warppipe_client *client))
 			                ^
```

**Comment by cfriedt** [comment]
The PR to adjust qemu is in antmicro/qemu#1

**Comment by kgugala** [comment]
> I should note that `checkpatch.pl` is pretty horrible with C++ syntax.
> 
> E.g. - this makes no sense fwict.
> 
> ```shell
> ERROR: need consistent spacing around '*' (ctx:WxV)
> #86: FILE: ./src/server.c:86:
> +			warppipe_client *client))
>  			                ^
> ```

this looks like a checkpatch bug/limitation. It gets confused by the function signature here - the second argument being a pointer to another function. Checkpatch processes the `*` in line 68 as multiplication operator, not as indirection operator. I suppose typedefing the function pointer should do the trick

**Review by cfriedt — COMMENTED** [review]
LGTM

**Pull request merged**
